a=("Python is a case sensitive language")
print(len(a))
print(a[::-1])
b=slice(10,26)
print(a[b])
c=a.replace("a case sensitive", "object oriented")
print(c)
d=a.index('a')
print(d)
e=a.replace(' ','')
print(e)